### ISSUE TITLE
Priority level - nice

### ISSUE THREAD

**Issue by adripo** [azinchen/duplicacy#145]
Hi, this is more like an information request, than an issue.
Why is there necessary to use nice inside the container? There are other methods to limit or prioritize the container itself instead of operating with the process inside the container.
I also found out that `nice` cannot work inside the container without granting `SYS_NICE` capability to the container.
https://docs.docker.com/config/containers/resource_constraints/#configure-the-docker-daemon

I would specify this information in the documentation if `nice` will be kept.

**Comment by pcrgarret** [comment]
For what it's worth I cannot initialize a repository on my Synology (DSM 7.1.1) and tracked it down to  line [container-init-up-20-init.sh#L35](https://github.com/azinchen/duplicacy/blob/fb07e9a80c8561bc498f6a9c08f75951966af076/root/usr/bin/container-init-up-20-init.sh#L35). Rolling back commit [bbed16f](https://github.com/azinchen/duplicacy/commit/bbed16f514ae9c1dab1724f41a4bda6854497940) solved the issue. I tried granting SYS_NICE to no avail; I suspect it is a limitation of DSM. Would you be open to making prioritization optional?

**Comment by pcrgarret** [comment]
> For what it's worth I cannot initialize a repository on my Synology (DSM 7.1.1) and tracked it down to line [container-init-up-20-init.sh#L35](https://github.com/azinchen/duplicacy/blob/fb07e9a80c8561bc498f6a9c08f75951966af076/root/usr/bin/container-init-up-20-init.sh#L35). Rolling back commit [bbed16f](https://github.com/azinchen/duplicacy/commit/bbed16f514ae9c1dab1724f41a4bda6854497940) solved the issue. I tried granting SYS_NICE to no avail; I suspect it is a limitation of DSM. Would you be open to making prioritization optional?

I'm afraid I've made a mistake. My issue was NOT to do with nice. It was late and I missed that in addition to removing nice I also added "cd /config" just before line 35 and THAT is what solved my issue. So initialization is failing for me because .duplicacy is being created in "/run/s6-rc:s6-rc-init:PAgNln/servicedirs/s6rc-oneshot-runner" rather than /config. And so downstream calls to backup.sh result in "Repository has not been initialized". I don't want to hijack this tread but any pointers would be appreciated.
